### ISSUE TITLE
Investigate and develop all possible missing segments

### ISSUE THREAD

**Issue by Chemaclass** [Chemaclass/edifact-parser#1]
Investigate and develop all possible or common segments that we should provide by default as part of this library inside `src/Segments`

**Comment by Jaimies** [comment]
Is this issue still relevant to you? I would not be able to investigate all the possible segments, but I would love to try to implement the ones I need to use in my project.

**Comment by Chemaclass** [comment]
Hi, @Jaimies! Thanks for your comment. That sounds great 👍 
Feel free to submit your PRs adding any new segments that could be useful for more people.

**Comment by Jaimies** [comment]
Could we start by adding support for newer PHP versions?

I checked, the library seems to run perfectly fine on PHP 8.1, can we just add 8.0 and 8.1 to the list of supported PHP versions in composer.json? Because it's a bit annoying that composer keeps complaining about that.

**Comment by Chemaclass** [comment]
Yeah, I will change the `composer.json` to support `>=8.0`

**Comment by Chemaclass** [comment]
There you go https://github.com/Chemaclass/EdifactParser/releases/tag/3.0.0 🥳

**Comment by Jaimies** [comment]
Thanks, @Chemaclass.

Btw, I've already implemented one of the segments (RFF), I'll make a pull request in a sec.

**Comment by Chemaclass** [comment]
I think we can close this one 🤔 Or is there something else that you consider we should do before closing it, @Jaimies?

**Comment by Chemaclass** [comment]
Feel free to open a PR if you want to add new segments.
