### ISSUE TITLE
Encoding error ?

### ISSUE THREAD

**Issue by tomjakobs1** [Chemaclass/edifact-parser#35]
Back on the script again, and trying to parse a edifact file. However i get an error if it contains nordic characters. æøå.  The scripts gives me an exception like this: ["There's a not printable character on line 17: NAD+CN+++Nes videregaende skole+Kjuushagen 3+\u00c5RNES.

The file is utf-8 encoded.
Any help appreciated :)

Thanks 
Tom

**Comment by Chemaclass** [comment]
Can you provide a bit more context and the code you're using? Maybe a similar file (removing sensible data) that you're trying to decode so I can reproduce the error? I will try reproducing later 😄

**Comment by tomjakobs1** [comment]
Hello. Could i send it on email ?

**Comment by Chemaclass** [comment]
No need for an email. I would like to have some file content where I can reproduce the error, so I can debug it.

You can create a file content with those chars, something simbolic that can help me to reproduce it. No need to have real or compromised data. 

>**Note**: Consider this example: https://github.com/Chemaclass/edifact-parser/blob/master/example/edifact-sample.edi 
<img width="613" alt="Screenshot 2023-02-22 at 13 52 39" src="https://user-images.githubusercontent.com/5256287/220624929-560a9617-5ce3-4104-91c7-3da984380e7f.png">

**Comment by tomjakobs1** [comment]
I think we actually found out the encoding issue. It was our editor that messed up the encoding.

**Comment by Chemaclass** [comment]
Even better! Then feel free to close the issue. Glad to help 😄
